CREATE TABLE IF NOT EXISTS `rag_retrieval_traces` (
  `id` VARCHAR(36) NOT NULL,
  `conversation_type` VARCHAR(16) NULL,
  `conversation_id` INT NULL,
  `message_id` INT NULL,
  `principal_role` VARCHAR(20) NULL,
  `principal_id` INT NULL,
  `query_hash` VARCHAR(64) NOT NULL,
  `mode` VARCHAR(24) NOT NULL DEFAULT 'knowledge_base',
  `release_id` VARCHAR(64) NULL,
  `status` VARCHAR(24) NOT NULL DEFAULT 'completed',
  `error_code` VARCHAR(64) NULL,
  `embedding_provider` VARCHAR(64) NULL,
  `embedding_model` VARCHAR(128) NULL,
  `embedding_schema_version` VARCHAR(128) NULL,
  `prompt_version` VARCHAR(64) NULL,
  `reranker_model` VARCHAR(255) NULL,
  `retrieval_config` JSON NULL,
  `candidate_counts` JSON NULL,
  `stage_durations_ms` JSON NULL,
  `token_usage` JSON NULL,
  `candidates` JSON NULL,
  `citation_map` JSON NULL,
  `created_at` DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  `completed_at` DATETIME(6) NULL,
  PRIMARY KEY (`id`),
  KEY `idx_rag_trace_created` (`created_at`),
  KEY `idx_rag_trace_release` (`release_id`),
  KEY `idx_rag_trace_status` (`status`),
  KEY `idx_rag_trace_conversation` (`conversation_id`),
  KEY `idx_rag_trace_message` (`message_id`),
  KEY `idx_rag_trace_principal` (`principal_id`),
  KEY `idx_rag_trace_query_hash` (`query_hash`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
